name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: dotnet run
      run: dotnet run --project ./OptimalTrafic/OptimalTrafic/OptimalTrafic.csproj 

    - name: dotnet build
      run: dotnet build --source ./OptimalTrafic/OptimalTrafic.sln